services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:homolog
    restart: always
    depends_on:
      - redis-evo
      - postgres-evo
      - rabbitmq-evo
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    env_file:
      - .env
    expose:
      - 8080

  redis-evo:
    container_name: redis-evo
    image: redis:latest
    restart: always
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

  postgres-evo:
    container_name: postgres-evo
    image: postgres:latest
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq-evo:
    container_name: rabbitmq-evo
    image: rabbitmq:management
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672 
  
  # minio-evo:
  #   image: quay.io/minio/minio
  #   command: server /data --console-address ":9001"
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - MINIO_ROOT_USER=USER
  #     - MINIO_ROOT_PASSWORD=PASSWORD
  #     - MINIO_BROWSER_REDIRECT_URL=http:/localhost:9001
  #     - MINIO_SERVER_URL=http://localhost:9000
  #   volumes:
  #     - minio_data:/data
  #   expose:
  #     - 9000
  #     - 9001

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:
  rabbitmq_data:
  # minio_data: